# Generated by Django 4.1.7 on 2023-02-23 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankMaster',
            fields=[
                ('bank_id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_website', models.URLField(blank=True, null=True)),
                ('bank_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_logo', models.ImageField(blank=True, null=True, upload_to='bank_logo')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBankAccount',
            fields=[
                ('account_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('cheque_image', models.ImageField(blank=True, null=True, upload_to='cheque_images')),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_cheque_verified', models.BooleanField(default=False)),
                ('name_as_per_bank_record', models.CharField(blank=True, max_length=100, null=True)),
                ('verification_mode', models.CharField(blank=True, max_length=20, null=True)),
                ('verification_status', models.CharField(blank=True, max_length=20, null=True)),
                ('account_type', models.CharField(blank=True, max_length=20, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.bankmaster')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
