# Generated by Django 4.1.7 on 2023-02-23 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_rename_bank_id_bankmaster_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankmaster',
            old_name='id',
            new_name='bank_id',
        ),
    ]
