# Generated by Django 4.1.7 on 2023-02-27 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0005_rename_id_bankmaster_bank_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerbankaccount",
            name="account_type",
            field=models.CharField(
                choices=[("Savings", "Savings"), ("Current", "Current")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="customerbankaccount",
            name="branch_name",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customerbankaccount",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="customerbankaccount",
            name="name_as_per_bank_record",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
