# Generated by Django 4.1.7 on 2023-02-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0006_alter_customerbankaccount_account_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerbankaccount",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
