# Generated by Django 4.1.7 on 2023-02-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0007_customerbankaccount_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerbankaccount",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=11,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customerbankaccount",
            name="account_number",
            field=models.CharField(max_length=20),
        ),
    ]
